name: Daily build

on:
  push:
   branches: [ main ]
# on:
#   schedule:
#     - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        poetry-version: ["1.4.0", "1.4.1", "1.4.2", "1.5.0", "1.5.1", "1.6.0", "1.6.1", "1.7.0", "1.7.1", "1.8.0", "1.8.1", "1.8.2"]
    steps:
      - uses: actions/checkout@v3
      - uses: docker-practice/actions-setup-docker@master
      - name: Run build
        run: |
          docker build --build-arg PYTHON_VERSION=${{ matrix.python-version }} --build-arg POETRY_VERSION=${{ matrix.poetry-version }} -f Dockerfile -t adamatics/pypoetry:${{ matrix.python-version }}-${{ matrix.poetry-version }} .
      - name: Push to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push adamatics/pypoetry:${{ matrix.python-version }}-${{ matrix.poetry-version }}